import type { Metadata } from "next";
import { Inter } from "next/font/google"
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "@/app/style/themes.css"
import StoreProvider from "./storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
                <body className={inter.className}>{children}</body>
      </StoreProvider>
    </html>
  );
}

